# Generated by Django 3.1.1 on 2020-09-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Houston', max_length=100),
            preserve_default=False,
        ),
    ]
