# Generated by Django 3.1.1 on 2020-09-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('main', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('temperatue', models.CharField(max_length=150)),
                ('wind', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
    ]
